# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nugetrelease

pool:
  vmImage: windows-latest

variables:
  project:  'SignalrMQ.Blazor/SignalrMQ.Blazor.csproj'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  MSBuildSDKsPath: 'C:\\hostedtoolcache\\windows\\dotnet\\sdk\\6.0.100-rc.2.21505.57\\sdks'


steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk RC2'
  inputs:
    packageType: 'sdk'
    version: '6.0.100-rc.2.21505.57'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(project)'


- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack 
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration)'
