# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nugetrelease

pool:
  vmImage: windows-latest

variables:
  project:  '**/*.csproj'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  MSBuildSDKsPath: 'C:\\hostedtoolcache\\windows\\dotnet\\sdk\\6.0.100\\sdks'


steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 6 sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.100'
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build 
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/SignalrMQ.Broker.csproj;**/SignalrMQ.Client.csproj;**/SignalrMQ.Core.csproj'
    versioningScheme: 'off'
    includeReferencedProjects: false
    includeSymbols: true

- task: NuGetCommand@2
  displayName: "nuget push"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3369fa02-658e-4673-b8a1-a747ff16848a'